version: '3.8'

services:
  # 1. The Postgres Database Service
  postgres_db:
    image: postgres:16-alpine
    container_name: library_postgres
    networks:
      - library_network
    environment:
      POSTGRES_USER: ashok
      POSTGRES_PASSWORD: ashok123!
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ashok -d library_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # 2. Your Go Application Service
  go_app:
    build: .
    container_name: library_app
    networks:
      - library_network
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      payment_service:
        condition: service_started
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=ashok
      - DB_PASSWORD=ashok123!
      - DB_NAME=library_db
      - PAYMENT_SERVICE_ADDRESS=payment_service:50051
      - REDIS_ADDRESS=redis:6379

  payment_service:
    build:
      context: .
      dockerfile: payment/Dockerfile
    container_name: payment_service
    networks:
      - library_network
    ports:
      - "50051:50051"
    depends_on:
      postgres_db:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: library_redis
    networks:
      - library_network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata: # This ensures your data isn't deleted when the container stops

networks:
  library_network:
    driver: bridge
